# Generated by Django 5.0.2 on 2024-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_BuyMedicine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="orderedmedicine",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medicines",
        ),
        migrations.RemoveField(
            model_name="prescribedmedicine",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="order",
            name="medicines",
        ),
        migrations.RemoveField(
            model_name="order",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="orderedmedicine",
            name="order",
        ),
        migrations.RemoveField(
            model_name="prescribedmedicine",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.AddField(
            model_name="patient",
            name="cabinNo",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="patient",
            name="patientId",
            field=models.CharField(
                default="", max_length=10, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=1
            ),
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Medicine",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderedMedicine",
        ),
        migrations.DeleteModel(
            name="PrescribedMedicine",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
    ]
