# Generated by Django 5.0.2 on 2024-02-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_BuyMedicine", "0003_medicine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="needed",
        ),
        migrations.AddField(
            model_name="medicine",
            name="inStock",
            field=models.BooleanField(default=False),
        ),
    ]
